# Question 1 - Data wrangling

In [1]:
import pandas as pd
import geopandas as gpd
import requests, json

## Joining census data with CalEnviroScreen shapefile

Here are the variables of interest:
- Median household income: B19013_001E
- Median gross rent: B25064_001E
- Units in housing: DP04_0006E to DP04_00013E
- Education attainment: S1501

First we get median household income and median gross rent from U.S. Census via an API request.

In [2]:
#we have to make a different request bc this variable isn't in the "profiles" subsection
rs = "https://api.census.gov/data/2020/acs/acs5?get=NAME,B19013_001E,B25064_001E&for=tract:*&in=state:06"
r = requests.get(rs)
d=json.loads(r.text)
IncomeRentDf = pd.DataFrame(d[1:], columns = d[0])

Then we repeat the same process, except this time we are pulling housing data from another dataset from the U.S. Census.

In [6]:
rs2 = "https://api.census.gov/data/2020/acs/acs5/profile?get=NAME,DP04_0006E,DP04_0007E,DP04_0008E,DP04_0009E,DP04_0010E,DP04_0011E,DP04_0012E,DP04_0013E&for=tract:*&in=state:06"
r2 = requests.get(rs2)
d2=json.loads(r2.text)
HousingDf = pd.DataFrame(d2[1:], columns = d2[0])

Here I generate all the variables I need from the S1501 table because the table is too big to process.

In [2]:
list = []
for i in range(1, 28):
    if (i < 10):
        print("S1501_C01_00" + str(i) + 'E' + ',', end = '')
        list.append("S1501_C01_00" + str(i) + 'E')
    else: 
        print("S1501_C01_0" + str(i) + 'E' + ',', end = '')
        list.append("S1501_C01_0" + str(i) + 'E')
print(list)

S1501_C01_001E,S1501_C01_002E,S1501_C01_003E,S1501_C01_004E,S1501_C01_005E,S1501_C01_006E,S1501_C01_007E,S1501_C01_008E,S1501_C01_009E,S1501_C01_010E,S1501_C01_011E,S1501_C01_012E,S1501_C01_013E,S1501_C01_014E,S1501_C01_015E,S1501_C01_016E,S1501_C01_017E,S1501_C01_018E,S1501_C01_019E,S1501_C01_020E,S1501_C01_021E,S1501_C01_022E,S1501_C01_023E,S1501_C01_024E,S1501_C01_025E,S1501_C01_026E,S1501_C01_027E,['S1501_C01_001E', 'S1501_C01_002E', 'S1501_C01_003E', 'S1501_C01_004E', 'S1501_C01_005E', 'S1501_C01_006E', 'S1501_C01_007E', 'S1501_C01_008E', 'S1501_C01_009E', 'S1501_C01_010E', 'S1501_C01_011E', 'S1501_C01_012E', 'S1501_C01_013E', 'S1501_C01_014E', 'S1501_C01_015E', 'S1501_C01_016E', 'S1501_C01_017E', 'S1501_C01_018E', 'S1501_C01_019E', 'S1501_C01_020E', 'S1501_C01_021E', 'S1501_C01_022E', 'S1501_C01_023E', 'S1501_C01_024E', 'S1501_C01_025E', 'S1501_C01_026E', 'S1501_C01_027E']

In [43]:
rs3 = "https://api.census.gov/data/2020/acs/acs5/subject?get=NAME,\
S1501_C01_001E,S1501_C01_002E,S1501_C01_003E,S1501_C01_004E,S1501_C01_005E,S1501_C01_006E,\
S1501_C01_007E,S1501_C01_008E,S1501_C01_009E,S1501_C01_010E,S1501_C01_011E,S1501_C01_012E,\
S1501_C01_013E,S1501_C01_014E,S1501_C01_015E,S1501_C01_016E,S1501_C01_017E,S1501_C01_018E,\
S1501_C01_019E,S1501_C01_020E,S1501_C01_021E,S1501_C01_022E,S1501_C01_023E,S1501_C01_024E,\
S1501_C01_025E,S1501_C01_026E,S1501_C01_027E\
&for=tract:*&in=state:06"
r3 = requests.get(rs3)
d3=json.loads(r3.text)
EducationDf = pd.DataFrame(d3[1:], columns = d3[0])

In [44]:
EducationDf.head()

,NAME,S1501_C01_001E,S1501_C01_002E,S1501_C01_003E,S1501_C01_004E,S1501_C01_005E,S1501_C01_006E,S1501_C01_007E,S1501_C01_008E,S1501_C01_009E,...,S1501_C01_021E,S1501_C01_022E,S1501_C01_023E,S1501_C01_024E,S1501_C01_025E,S1501_C01_026E,S1501_C01_027E,state,county,tract
0,"Census Tract 3131.02, Contra Costa County, Cal...",433,23,171,228,11,3034,183,246,834,...,159,1064,929,107,683,506,108,06,013,313102
1,"Census Tract 3131.04, Contra Costa County, Cal...",343,0,220,90,33,1962,310,388,780,...,62,637,318,74,304,207,18,06,013,313104
2,"Census Tract 3131.05, Contra Costa County, Cal...",564,78,260,211,15,3087,281,370,888,...,104,974,876,160,853,698,195,06,013,313105
3,"Census Tract 3131.06, Contra Costa County, Cal...",992,43,306,497,146,4479,183,302,1035,...,300,1847,1649,476,668,569,209,06,013,313106
4,"Census Tract 3131.07, Contra Costa County, Cal...",197,41,116,20,20,1782,82,75,511,...,130,583,500,135,391,373,111,06,013,313107

We then renamed the columns to make them more Readable.

In [45]:
IncomeRentDf.rename(columns = {'B19013_001E': 'Median Income', 'B25064_001E': 'Median Rent'}, inplace= True)

We create a `GEOID` column by combining the `state`, `county`, and `tract` column in preparation for a tabular join.

In [46]:
columns = ['tract', 'county', 'state']
for i in columns:
    IncomeRentDf[i] = IncomeRentDf[i].astype(str)
    HousingDf[i] = HousingDf[i].astype(str)
    EducationDf[i] = EducationDf[i].astype(str)
HousingDf['GEOID'] = HousingDf['state'] + HousingDf['county'] + HousingDf['tract']
HousingDf['GEOID'] = HousingDf['GEOID'].astype(int)
IncomeRentDf['GEOID'] = IncomeRentDf['state'] + IncomeRentDf['county'] + IncomeRentDf['tract']
IncomeRentDf['GEOID'] = IncomeRentDf['GEOID'].astype(int)
EducationDf['GEOID'] = EducationDf['state'] + IncomeRentDf['county'] + IncomeRentDf['tract']
EducationDf['GEOID'] = EducationDf['GEOID'].astype(int)

Here we join `HousingDf` and `IncomeRentDf` and `EducationDf` to a new dataframe - `censusDf`.

In [50]:
censusDf = HousingDf.set_index("GEOID").join(IncomeRentDf.set_index("GEOID"), rsuffix = '_remove').join(EducationDf.set_index("GEOID"), rsuffix = '_remove1')
#dropping duplicate and useless columns
censusDf.drop(columns = ['NAME', 'NAME_remove', 'state', 'state_remove', 'county', 'county_remove', 'tract', 'tract_remove', 'state_remove1' ,'county_remove1',	'tract_remove1'], inplace = True)

In [51]:
censusDf

,DP04_0006E,DP04_0007E,DP04_0008E,DP04_0009E,DP04_0010E,DP04_0011E,DP04_0012E,DP04_0013E,Median Income,Median Rent,...,S1501_C01_018E,S1501_C01_019E,S1501_C01_020E,S1501_C01_021E,S1501_C01_022E,S1501_C01_023E,S1501_C01_024E,S1501_C01_025E,S1501_C01_026E,S1501_C01_027E
GEOID,,,,,,,,,,,,,,,,,,,,,
6013313102,1554,626,182,12,145,205,24,347,78856,1958,...,182,445,436,159,1064,929,107,683,506,108
6013313104,964,391,47,0,13,134,70,309,48316,1804,...,60,374,175,62,637,318,74,304,207,18
6013313105,1837,921,35,15,154,274,84,130,62422,1732,...,68,638,381,104,974,876,160,853,698,195
6013313106,2033,1492,33,106,71,46,177,108,130091,2155,...,293,801,748,300,1847,1649,476,668,569,209
6013313107,782,762,0,0,0,0,0,20,122727,2192,...,74,368,330,130,583,500,135,391,373,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6111003902,836,673,32,0,0,0,28,103,52188,1395,...,337,496,496,399,1382,1379,593,850,818,463
6111004000,1381,1045,67,0,0,30,0,21,61645,1896,...,22,8,8,8,4,4,4,0,0,0
6111004101,1376,1105,13,0,37,40,85,85,74659,1644,...,3,8,8,8,15,15,13,0,0,0
6111004200,1383,1275,49,0,0,26,9,0,91889,1843,...,202,0,0,0,14,14,14,9,9,3
6111004304,2707,387,1245,0,537,172,91,275,71020,1672,...,96,161,151,141,190,180,143,86,86,56

Here we create a geodataframe for the CalEnviroscreen 4.0 data by reading a shapefile retrieved from [OEHHA](https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40).

In [52]:
CalEnviroScreenGdf = gpd.read_file('data/CES4/CES4 Final Shapefile.shp')
CalEnviroScreenGdf['Tract'] = CalEnviroScreenGdf['Tract'].astype(int)

We then join `CalEnviroScreenGdf` and `censusDf` into `tractsDf`.

In [53]:
tractsDf = CalEnviroScreenGdf.set_index('Tract').join(censusDf, how='left')

# Wrangling EV charger data

First, we requested data via an API from NREL and selected only electric vehicle chargers that are located in California.

In [ ]:
#optional code
#have to run this to fix my geopandas for some reason; if yours works don't run it
##solution from https://gis.stackexchange.com/questions/375361/zonal-stats-returns-proj-error
import os
import pyproj as p
os.environ['PROJ_LIB'] = '/Users/hfrahn/opt/anaconda3/envs/uds/bin/pyproj'
p.datadir.set_data_dir('/Users/hfrahn/opt/anaconda3/envs/uds/bin/pyproj')

In [54]:
#request chargers from NREL 
apiKey = "eCN7llpPT79TmygqmvC71QdnnWdOquoRdnCR1DXo"
nrelString = "https://developer.nrel.gov/api/alt-fuel-stations/v1.geojson?api_key={}&fuel_type=ELEC&state=CA".format(apiKey)
chargers = gpd.read_file(nrelString)

We filtered and keep only chargers that are accessible to the public.

In [56]:
chargers = chargers[chargers['access_code'] == 'public']

We can filter and keep only chargers that are accessible to the public.

In [58]:
chargers_sjoin = gpd.sjoin(tractsDf, chargers.to_crs('EPSG:3310'), how="inner", predicate='intersects')
chargers_sjoin.head()

,ZIP,County,ApproxLoc,TotPop19,CIscore,CIscoreP,Ozone,OzoneP,PM2_5,PM2_5_P,...,ng_fill_type_code,ng_psi,ng_vehicle_class,access_days_time_fr,intersection_directions_fr,bd_blends_fr,groups_with_access_code_fr,ev_pricing_fr,ev_network_ids,federal_agency
Tract,,,,,,,,,,,,,,,,,,,,,
6083002103,93454,Santa Barbara,Santa Maria,4495,36.019653,69.162885,0.03419,10.566273,7.567724,10.031114,...,None,None,None,None,None,None,Public,None,"{'station': ['837'], 'posts': ['110112-01', '1...",None
6083002103,93454,Santa Barbara,Santa Maria,4495,36.019653,69.162885,0.03419,10.566273,7.567724,10.031114,...,None,None,None,None,None,None,Public,None,None,None
6083002103,93454,Santa Barbara,Santa Maria,4495,36.019653,69.162885,0.03419,10.566273,7.567724,10.031114,...,None,None,None,None,None,None,Public,None,"{'station': ['USCPIL7823641'], 'posts': ['1357...",None
6083002103,93454,Santa Barbara,Santa Maria,4495,36.019653,69.162885,0.03419,10.566273,7.567724,10.031114,...,None,None,None,None,None,None,Public,None,"{'station': ['USCPIL7823791'], 'posts': ['1357...",None
6083002103,93454,Santa Barbara,Santa Maria,4495,36.019653,69.162885,0.03419,10.566273,7.567724,10.031114,...,None,None,None,None,None,None,Public,None,"{'station': ['USCPIL7821621'], 'posts': ['1357...",None

Below we use `groupby` to aggregate the number of EV chargers per census tract.

In [18]:
chargers_by_tract = chargers_sjoin.reset_index().groupby(['Tract'])['Tract'].count()

In [21]:
chargers_by_tract = chargers_by_tract.to_frame().rename(columns = {'Tract': 'Charger count'})
chargers_by_tract['Charger count'] = chargers_by_tract['Charger count'].astype('int16')

We then joined `chargers_by_tract` dataframe to `tractsDf` in preparation for predictive modeling.

In [22]:
joinedDf = tractsDf.join(chargers_by_tract, how = 'left')

Replace `NaN`s in `count` with `0`s

In [24]:
joinedDf['Charger count'] = joinedDf['Charger count'].fillna(0)

We then export `joinedDf` as a GeoJson file for further visualization and analysis in the main notebook.

In [25]:
joinedDf.to_file('data/joinedDf.geojson', driver='GeoJSON')